---
      - name: Launch the new EC2 Instanc
        local_action: ec2 
                      group=ishan-assignment 
                      instance_type=t2.micro
                      image=ami-04ea996e7a3e7ad6b
                      region=ap-south-1	
                      keypair=ishan-assignment
                      count="{{ shard2 }}"
        register: ec2c

      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region=ap-south-1 state=present
        with_items: "{{ ec2c.instances }}"
        args:
          tags:
            Name: shard2

      - name: Add the newly created EC2 instance(s) to host group
        lineinfile:
              dest: /etc/ansible/hosts
              line: '{{ item.private_ip }}'
              insertafter: '\[shard2\]'
        with_items: ec2c.instances

      - name: add IPs to the group_vars file
        lineinfile:
           dest: /etc/ansible/group_vars/shard2
           line: ' sha2_{{ item.ami_launch_index }}: {{ item.private_ip }}'
           state: present
        with_items: "{{ ec2c.instances }}"

