---
      - name: Launch the new EC2 Instanc
        local_action: ec2 
                      group=ishan-assignment 
                      instance_type="{{ type }}"
                      image="{{ image }}"
                      region="{{ region }}"
                      wait=yes	
                      keypair=ishan-assignment
                      count=2
        register: ec2c

      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region="{{ region }}" state=present
        with_items: "{{ ec2c.instances }}"
        args:
          tags:
            Name: shard2

      - name: Add the newly created EC2 instance(s) to host group
        lineinfile:
              dest: /etc/ansible/hosts
              line: '{{ item.private_ip }}'
              insertafter: '\[shard2\]'
        with_items: ec2c.instances

      - name: add IPs to the group_vars file
        lineinfile:
           dest: /etc/ansible/group_vars/shard2
           line: ' sha2_{{ item.ami_launch_index }}: {{ item.private_ip }}'
           state: present
        with_items: "{{ ec2c.instances }}"


      - name: add IPs to the group_vars file
        lineinfile:
           dest: /etc/ansible/group_vars/mongos
           line: ' sha2_{{ item.ami_launch_index }}: {{ item.private_ip }}'
           state: present
        with_items: "{{ ec2c.instances }}"


      - name: Waiting for the instance to come
        local_action: wait_for
              host={{ item.private_ip }}
              state=started
              port=22
        with_items: ec2c.instance


      - name: Wait for SSH to come up
        local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
        with_items: ec2c.instances
